// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcHuBgnZtMIZgFbfFzv2ZZNC9rX3txq1o',
    appId: '1:631614180987:web:88ea01ea9dbaf4a1899cde',
    messagingSenderId: '631614180987',
    projectId: 'ta-umkm-mart',
    authDomain: 'ta-umkm-mart.firebaseapp.com',
    storageBucket: 'ta-umkm-mart.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxg83CkruRt0TDe6dK_9B6qT95NrSNbaY',
    appId: '1:631614180987:android:f483cb98ee4290ff899cde',
    messagingSenderId: '631614180987',
    projectId: 'ta-umkm-mart',
    storageBucket: 'ta-umkm-mart.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnKLKM17CirAAkRdr1T5VgfvUIQsWuX70',
    appId: '1:631614180987:ios:b260af35fcc583ee899cde',
    messagingSenderId: '631614180987',
    projectId: 'ta-umkm-mart',
    storageBucket: 'ta-umkm-mart.appspot.com',
    androidClientId: '631614180987-in2v63sa01vsrrcfa95bphbvut8gl1b6.apps.googleusercontent.com',
    iosClientId: '631614180987-pr2o1ec0pbjn3n6q4eqg0223t3ur6vj4.apps.googleusercontent.com',
    iosBundleId: 'com.example.taEcommerce',
  );
}
